version: 2.1

setup: false

orbs:
  node: circleci/node@5.04

commands:
  test-command:
    description: This is a test command.
    parameters:
      name:
        description: A name of some kind.
        type: string
        default: Some Default
    steps: # REQUIRED
      - checkout
      - restore_cache:
          key: circleci-docs-v1-{{ .Branch }}-<< parameters.dir >>-{{ checksum "Gemfile.lock" }}
      - run:
          name: Do a thing
          command: ls -al
      - save_cache:
          key: circleci-docs-v1-{{ .Branch }}-<< parameters.dir >>-{{ checksum "Gemfile.lock" }}
          paths:
            - "vendor/bundle"
            - "<< parameters.dir >>/vendor/bundle" # TODO Figure out some other common steps

parameters:
  test-parameter: # NOTE Same structure as parameters in commands.
    description: This is a test parameter.
    type: string # REQUIRED string, boolean, integer, enum, executor, steps, env_var_name
    default: Some Param Default # NOTE If not provided, parameter is required
  test-enum-parameter:
    description: This is a test enum parameter.
    type: enum
    default: Some Enum Default
    enum: ["a", "b", "c"]
  test-executor-parameter:
    description: This is a test executor parameter.
    type: executor # TODO https://circleci.com/docs/reusing-config/#executor
  test-steps-parameter:
    description: This is a test steps parameter.
    type: steps
    default: [] # TODO https://circleci.com/docs/reusing-config/#steps
  test-env-var-parameter:
    description: This is a test env var parameter.
    type: env_var_name
    default: SOME_ENV_VAR

executors:
  test-executor-docker:
    docker:
      - image: cimg/base:2020.01 # REQUIRED
      - name: My Name
      - entrypoint: entrypoint # or list
      - command: command # or list
      - user: user
      - environment:
          A: A
          B: B
      - auth:
          username: username
          password: password
      - aws_auth:
          oidc_role_arn: oidc_role_arn
          # or
          aws_access_key_id: aws_access_key_id
          aws_secret_access_key: aws_secret_access_key
    resource_class: xlarge # NOTE Best as a string for now, but could be scoped to an enum
    shell: /bin/sh
    working_directory: /path/to/working/directory
    environment:
      A: A
      B: B
  test-executor-macos:
    xcode: "14.2.0" # REQUIRED
  test-executor-machine:
    machine:
      image: ubuntu-2004:current # REQUIRED
      docker_layer_caching: true # boolean

jobs:
  test-job:
    steps:
      - test-command:
          name: My Name
# CHECKPOINT
# https://circleci.com/docs/configuration-reference/#jobs
# https://circleci.com/docs/reusing-config/#authoring-reusable-executors
